### ISSUE TITLE
Create a Portuguese translation of the navigate terminal guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#106]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/navigate-terminal.md), create a Portuguese translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/pt/guides/navigate-terminal.md.

It is OK to use the English images/GIFs. Look for `TODO` in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by amimaro** [comment]
Hi! May I work on this one?

**Comment by devadvance** [comment]
@amimaro sure! I assigned it to you.

**Comment by amimaro** [comment]
Thank you!
