### ISSUE TITLE
Create a Portuguese translation of the curl REST API guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#108]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/curl-rest-api.md), create a Portuguese translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/pt/guides/curl-rest-api.md.

It is OK to use the English images/GIFs. Look for `TODO` in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by amimaro** [comment]
Hi! May I translate this one too?

**Comment by devadvance** [comment]
@amimaro sure thing, assigning to you.
