### ISSUE TITLE
Create a Portuguese translation of the basic web server guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#109]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/basic-web-server-macos-linux.md), create a Portuguese translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/pt/guides/basic-web-server-macos-linux.md.

It is OK to use the English images/GIFs. Look for `TODO` in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by mihmilicio** [comment]
I can do that!

**Comment by devadvance** [comment]
@mihmilicio assigned this to you.

**Comment by mihmilicio** [comment]
@devadvance just a question: do you need it in Portuguese from Portugal or can it be Brazilian Portuguese?

**Comment by devadvance** [comment]
@mihmilicio great question! It can be in either. Eventually, we may need to split since there are differences, but for v1, either is OK. Obrigado por verificar!

**Comment by mihmilicio** [comment]
Submitted my PR for this issue! Please review and keep this in mind: https://hacktoberfest.digitalocean.com/hacktoberfest-update
