### ISSUE TITLE
Create a Portuguese translation of the open terminal guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#110]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/open-terminal-macos.md), create a Portuguese translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/pt/guides/open-terminal-macos.md.

It is OK to use the English images/GIFs. Look for `TODO` in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by gianpablo** [comment]
I can do that.

**Comment by devadvance** [comment]
@gianpablo assigned this to you!

**Comment by gianpablo** [comment]
Hi Matt,
I am new to GitHub, can you see my commits?
Just to make sure I am doing this in the right way.
Thanks

**Comment by devadvance** [comment]
I can't see them yet. You need to commit them to a branch on your fork, and then PR that branch to this main repo.

**Comment by devadvance** [comment]
@gianpablo let me know if you need assistance with this!

**Comment by gianpablo** [comment]
Ok, @devadvance. I'm gonna check this in a couple of hours and ask for your help if needed. Thanks!

**Comment by gianpablo** [comment]
Hi @devadvance . I PR that branch. Could you check if I did this correctly? I am not sure this is going to the correct folder and gonna be merged with the right file. Thanks!

**Comment by gianpablo** [comment]
Also one of the branches is showing some conflict I could not identify.
