### ISSUE TITLE
Create a Telugu translation of the navigate terminal guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#111]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/navigate-terminal.md), create a Telugu translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/te/guides/navigate-terminal.md.

It is OK to use the English images/GIFs. Look for `TODO` in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by shanmukhkalasamudram** [comment]
I'm Interested to do this, I'm a native speaker

**Comment by devadvance** [comment]
@shanmukhkalasamudram assigning to you!

**Comment by shanmukhkalasamudram** [comment]
Its done. Can you check it.
