### ISSUE TITLE
Create a Telugu translation of the curl REST API guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#112]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/curl-rest-api.md), create a Telugu translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/te/guides/curl-rest-api.md.

It is OK to use the English images/GIFs. Look for `TODO` in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by IMPrimph** [comment]
@devadvance 
I am a native speaker, I am interested in this!

**Comment by devadvance** [comment]
@IMPrimph that would be very helpful! I am assigning this to you.

**Comment by IMPrimph** [comment]
Ok, thank you.
Will do it and let you know!

**Comment by IMPrimph** [comment]
@devadvance 
Done!
