### ISSUE TITLE
Create a Telugu translation of the basic web server guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#113]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/basic-web-server-macos-linux.md), create a Telugu translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/te/guides/basic-web-server-macos-linux.md.

It is OK to use the English images/GIFs. Look for `TODO` in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by manishkrjha** [comment]
So, we have to translate the page file in <a href="https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/basic-web-server-macos-linux.md">First link</a> and store it in <a href="https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/te/guides/basic-web-server-macos-linux.md">second</a> ?

I can do this if this is unassigned yet

**Comment by devadvance** [comment]
@manishkrjha yes that is the objective. Assigning this issue to you.
