### ISSUE TITLE
Create a Telugu translation of the open terminal guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#114]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/open-terminal-macos.md), create a Telugu translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/te/guides/open-terminal-macos.md.

It is OK to use the English images/GIFs. Look for `TODO` in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by manishkrjha** [comment]
I can do this

**Comment by devadvance** [comment]
@manishkrjha assigning this issue to you.

**Comment by devadvance** [comment]
Fixed in #141
