### ISSUE TITLE
Add Portuguese translations for file command descriptions

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#115]
This issue is to add Portuguese translations for the existing commands found in https://github.com/devadvance/terminalcheatsheet/blob/staging/_data/commands/files.yml

Use `pt` (the locale code for Portuguese) as the key for the strings.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by rhikson** [comment]
I'm working on it!
