### ISSUE TITLE
Create a Indonesian translation of the basic web server guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#116]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/basic-web-server-macos-linux.md), create a Indonesian translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/id/guides/basic-web-server-macos-linux.md.

It is OK to use the English images/GIFs. Look for `TODO` in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by AjiArya** [comment]
@devadvance I'm working on it

**Comment by devadvance** [comment]
@AjiArya assigning to you then!
