### ISSUE TITLE
Create a Indonesian translation of the curl REST API guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#117]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/curl-rest-api.md), create a Indonesian translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/id/guides/curl-rest-api.md.

It is OK to use the English images/GIFs. Look for `TODO` in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by Aldhanekaa** [comment]
Can I work for this translation? 
And If I can, When the deadline?

**Comment by Aldhanekaa** [comment]
may I work on this translation?

**Comment by devadvance** [comment]
@Aldhanekaa sure! Assigned to you.

**Comment by Aldhanekaa** [comment]
![Screen Shot 2020-10-05 at 05 58 05](https://user-images.githubusercontent.com/67791514/95029290-5f325e00-06d1-11eb-864f-8680cb4ddd4b.png)
Is the AMP validation had errors because of the Http address?

but after opening Learn more they guide me to change something in code. I shouldn't do that, right?

Is the problem will solve when the site doesn't have Http address (Using GitHub page)?

**Comment by Aldhanekaa** [comment]
> ![Screen Shot 2020-10-05 at 05 58 05](https://user-images.githubusercontent.com/67791514/95029290-5f325e00-06d1-11eb-864f-8680cb4ddd4b.png)
> Is the AMP validation had errors because of the Http address?
> 
> but after opening Learn more they guide me to change something in code. I shouldn't do that, right?
> 
> Is the problem will solve when the site doesn't have Http address (Using GitHub page)?

Actually I already translated it, but doubt to pull request because of that error.

**Comment by devadvance** [comment]
@Aldhanekaa that error is fine. During local development, the content is `http` instead of `https`. If there are no other errors, then it is ready for PR!

**Comment by Aldhanekaa** [comment]
#139

**Comment by Aldhanekaa** [comment]
#139

**Comment by devadvance** [comment]
Reviewed and merged. Thanks for contributing!!
