### ISSUE TITLE
Create a Indonesian translation of the navigate terminal guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#118]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/navigate-terminal.md), create a Indonesian translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/id/guides/navigate-terminal.md.

It is OK to use the English images/GIFs. Look for `TODO` in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by ilesmana** [comment]
I'm working on it.
