### ISSUE TITLE
Create a Indonesian translation of the open terminal guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#119]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/open-terminal-macos.md), create a Indonesian translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/id/guides/open-terminal-macos.md.

It is OK to use the English images/GIFs. Look for `TODO` in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by ilesmana** [comment]
Hi @devadvance , I can do this

**Comment by devadvance** [comment]
@ilesmana fantastic! Assigning to you.

**Comment by ilesmana** [comment]
@devadvance , pls check the PR #122

**Comment by devadvance** [comment]
Fixed by #137
