### ISSUE TITLE
Implement copy button and show me buttons as includes

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#12]
We should move the actual code for each of these buttons into includes. They can then get their data via parameters: https://jekyllrb.com/docs/includes/#passing-parameters-to-includes

**Comment by ilesmana** [comment]
hi @devadvance , I've implemented this enhancement. Let me know if you want to assign this issue, so I can create a PR

**Comment by devadvance** [comment]
@ilesmana sure thing! Assigning this one to you as well.
