### ISSUE TITLE
Add Japanese translations for general strings

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#147]
This issue is to add Japanese translations for the existing strings found in https://github.com/devadvance/terminalcheatsheet/blob/staging/_data/translations.yml

Use `ja` (the locale code for Japanese) as the key for the strings. Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by hakuamesan** [comment]
Hi, I would like to translate the Japanese text. Can you assign this to me? Thanks!
