### ISSUE TITLE
Add Bengali (Bangla) translations for general strings

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#148]
This issue is to add Bengali (Bangla) translations for the existing strings found in https://github.com/devadvance/terminalcheatsheet/blob/staging/_data/translations.yml

Use `bn` (the locale code for Bengali (Bangla)) as the key for the strings. Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by krishnasreekoganti** [comment]
@devadvance Hi can I work on this?

**Comment by krishnasreekoganti** [comment]
@devadvance I started working on this can you please assign this to me I will raise a PR soon
