### ISSUE TITLE
Add Chinese (Simplified) translations for general strings

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#149]
This issue is to add Chinese (Simplified) translations for the existing strings found in https://github.com/devadvance/terminalcheatsheet/blob/staging/_data/translations.yml

Use `zh-CN` (the locale code for Chinese (Simplified)) as the key for the strings. Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by jswildcards** [comment]
Hi, I would like to translate it. Can you assign the work to me? Thanks! 😃

**Comment by devadvance** [comment]
@jswildcards sure thing! Assigned to you!
