### ISSUE TITLE
Add Japanese translations for command descriptions

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#166]
This issue is to add Japanese translations for the existing commands found in https://github.com/devadvance/terminalcheatsheet/tree/staging/_data/commands

Use `ja` (the locale code for Japanese) as the key for the strings.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by NickCwh** [comment]
Hi @devadvance I'll add in the Japanese translations for the strings will commit in a bit :)

**Comment by NickCwh** [comment]
Apologies for the emails and issue opening, the next commit will fix them.
