### ISSUE TITLE
Add Bengali (Bangla) translations for command descriptions

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#168]
This issue is to add Bengali (Bangla) translations for the existing commands found in https://github.com/devadvance/terminalcheatsheet/tree/staging/_data/commands

Use `bn` (the locale code for Bengali (Bangla)) as the key for the strings.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by Reghill** [comment]
Hi @devadvance , can you please assign this to me? I can work on it. Thanks

**Comment by Reghill** [comment]
Thanks for assigning it to me. I have created a pull request for the same #174

**Comment by devadvance** [comment]
Merged in #174
