### ISSUE TITLE
Add Tamil translations for command descriptions 

### ISSUE THREAD

**Issue by Reghill** [devadvance/terminalcheatsheet#175]
This issue is to add Tamil translations for the existing commands found in https://github.com/devadvance/terminalcheatsheet/tree/staging/_data/commands

Use ta (the locale code for Tamil) as the key for the strings.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by Reghill** [comment]
Can you assign this to me? I can work on this as well. Thanks in advance.

**Comment by devadvance** [comment]
Assigned!
