### ISSUE TITLE
Create a Chinese (Simplified) translation of the basic web server guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#176]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/basic-web-server-macos-linux.md), create a Chinese (Simplified) translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/zh-CN/guides/basic-web-server-macos-linux.md.

You can copy this template to use a starting point: https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/new_language_templates/guides/basic-web-server-macos-linux.md

It is OK to use the English images/GIFs. Look for `TODO` in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by NickCwh** [comment]
Thanks for accepting my PullRequests @devadvance

**Comment by NickCwh** [comment]
Thanks for accepting my previous pull requests for the Chinese translations @devadvance hopefully it can be useful to Chinese readers. I can take this

**Comment by devadvance** [comment]
@NickCwh Sounds good to me! Thank you for taking these 😄
