### ISSUE TITLE
Create a Chinese (Simplified) translation of the curl REST API guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#177]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/curl-rest-api.md), create a Chinese (Simplified) translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/zh-CN/guides/curl-rest-api.md.

You can copy this template to use a starting point: https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/new_language_templates/guides/curl-rest-api.md

It is OK to use the English images/GIFs. Look for `TODO` in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by NickCwh** [comment]
I can take this on, give me awhile to do the proper translations :)

**Comment by devadvance** [comment]
@NickCwh awesome! Assigning to you! Proper translations is what we're looking for 😄
