### ISSUE TITLE
Create a Chinese (Simplified) translation of the 404 error page

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#180]
Based on the English version of the 404 error page (https://github.com/devadvance/terminalcheatsheet/blob/staging/404.html), create a Chinese (Simplified) translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/zh-CN/404.html.

You can copy this template to use a starting point: https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/new_language_templates/404.html

Look for `TODO` in the file for suggested places for translations. Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by HelloSeaNation** [comment]
I would like to work on this task.

**Comment by HelloSeaNation** [comment]
@devadvance, changes done and PR submitted. Please check and let me know if anything I can help to close this issue.
