### ISSUE TITLE
Create a Bengali (Bangla) translation of the 404 error page

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#185]
Based on the English version of the 404 error page (https://github.com/devadvance/terminalcheatsheet/blob/staging/404.html), create a Bengali (Bangla) translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/bn/404.html.

You can copy this template to use a starting point: https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/new_language_templates/404.html

Look for `TODO` in the file for suggested places for translations. Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by JorgeMadson** [comment]
I will try it!

**Comment by JorgeMadson** [comment]
Done.

**Comment by JorgeMadson** [comment]
Any news on this?
