### ISSUE TITLE
Add Russian translations for command description strings

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#186]
This issue is to add Russian translations for the existing commands found in these two files:

* https://github.com/devadvance/terminalcheatsheet/blob/staging/_data/commands/files.yml
* https://github.com/devadvance/terminalcheatsheet/blob/staging/_data/commands/basic.yml

Use `ru` (the locale code for Russian) as the key for the strings. Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by Reghill** [comment]
Can you please assign this to me? I can work on it . thanks

**Comment by Reghill** [comment]
Thanks @devadvance . I have created pull request for the same- #192
