### ISSUE TITLE
Add translations for command descriptions in Hindi

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#60]
Add translations for the existing commands found in https://github.com/devadvance/terminalcheatsheet/tree/master/_data/commands

**Comment by Rookie3109** [comment]
Hey! I can translate this to Hindi, please assign it to me :) 
Thanks in advance.

**Comment by devadvance** [comment]
Fixed in #74. Great work!

**Comment by Rookie3109** [comment]
Thank you!
