### ISSUE TITLE
Add translations for command descriptions in French

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#61]
Add translations for the existing commands found in https://github.com/devadvance/terminalcheatsheet/tree/staging/_data/commands

**Comment by apjama** [comment]
Hey could you assign this to me please? I also noticed that the formatting on the Arabic translations is a bit off, particularly ones that include both English and Arabic words in them.

**Comment by devadvance** [comment]
Sure thing. The translations are Yemeni Arabic, so that might cause some of the difference.

**Comment by devadvance** [comment]
@apjama let me know if you are still able to work on this issue.
