### ISSUE TITLE
Create a Hindi translation of the basic web server guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#65]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/basic-web-server-macos-linux.md), create a Hindi translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/hi/guides/basic-web-server-macos-linux.md.

It is OK to use the English images/GIFs.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by NishithP2004** [comment]
Hi, Can you please assign me to this as well... I'm working on it ..
