### ISSUE TITLE
Create a Hindi translation of the curl REST API guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#66]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/curl-rest-api.md), create a Hindi translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/hi/guides/curl-rest-api.md.

It is OK to use the English images/GIFs.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by IMPrimph** [comment]
@devadvance 
Can you assign this to me?

**Comment by devadvance** [comment]
@IMPrimph yes, done!

**Comment by IMPrimph** [comment]
Ok, will do it and let you know 👍

**Comment by IMPrimph** [comment]
@devadvance 
Done!

**Comment by IMPrimph** [comment]
@devadvance 
Can you please accept the pull request and review if there are any changes
For hactoberfest, this would be my 4/4 PR
So, I can complete the contest
Thank you
