### ISSUE TITLE
Create a Hindi translation of the navigate terminal guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#67]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/navigate-terminal.md), create a Hindi translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/hi/guides/navigate-terminal.md.

It is OK to use the English images/GIFs.

**Comment by NishithP2004** [comment]
Can I work on this as well?
