### ISSUE TITLE
Create a French translation of the basic web server guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#69]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/basic-web-server-macos-linux.md), create a French translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/fr/guides/basic-web-server-macos-linux.md.

It is OK to use the English images/GIFs.

**Comment by AzogBiceps** [comment]
Hey, it's done!

**Comment by devadvance** [comment]
Fixed in #79
