### ISSUE TITLE
Create a French translation of the curl REST API guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#70]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/curl-rest-api.md), create a French translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/fr/guides/curl-rest-api.md.

It is OK to use the English images/GIFs.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by ArnolFokam** [comment]
Hello @devadvance I can help you with this issue. Would you mind assigning it to me?

**Comment by devadvance** [comment]
@ArnolFokam fantastic! I assigned it to you.
