### ISSUE TITLE
Create a French translation of the navigate terminal guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#71]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/navigate-terminal.md), create a French translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/fr/guides/navigate-terminal.md.

It is OK to use the English images/GIFs.

**Comment by iamlordutkarsh** [comment]
I would like To work on this

**Comment by iamlordutkarsh** [comment]
We Have To Translate it into French

**Comment by devadvance** [comment]
Sure thing! Assigned this issue to you.

**Comment by iamlordutkarsh** [comment]
Thanks
