### ISSUE TITLE
Create a French translation of the open terminal guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#72]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/open-terminal-macos.md), create a French translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/fr/guides/open-terminal-macos.md.

It is OK to use the English images/GIFs.

**Comment by beltzawoo** [comment]
Will take care of this! Give me just a moment

**Comment by beltzawoo** [comment]
There you go! I'm not sure if I did everything right with the pull request, so let me know if any changes are required!
