### ISSUE TITLE
Create a French translation of the 404 error page

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#80]
Based on the English version of the 404 error page (https://github.com/devadvance/terminalcheatsheet/blob/staging/404.html), create a French translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/fr/404.html.

Look for `TODO` in the file for suggested places for translations.

**Comment by ArnolFokam** [comment]
Hello @devadvance Can you assign me this issue? (J'aimerais beaucoup travailler dessus)

**Comment by fritssasia** [comment]
Hello @devadvance , do you need a translation in Indonesian language too? please let me know
Thank you :)

**Comment by devadvance** [comment]
@fritssasia I would appreciate it! If you comment on issue #90, I'll assign it to you.

**Comment by devadvance** [comment]
@ArnolFokam PR is merged! Merci pour la contribution!
