### ISSUE TITLE
Create a Hindi translation of the 404 error page

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#81]
Based on the English version of the 404 error page (https://github.com/devadvance/terminalcheatsheet/blob/staging/404.html), create a Hindi translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/hi/404.html.

Look for `TODO` in the file for suggested places for translations.

**Comment by NishithP2004** [comment]
Hi, could you please assign me to this issue?

**Comment by devadvance** [comment]
Assigned and will review the PR shortly.

**Comment by devadvance** [comment]
Translations are in, thanks!
