### ISSUE TITLE
Create a Telugu translation for the 404 error page

### ISSUE THREAD

**Issue by GiriAakula** [devadvance/terminalcheatsheet#84]
I see that you are translating this project into various languages. As my native language is telugu, I can do telugu translation for you. If you are ok with that, please confirm. Of course I'm doing this as part of Hacktoberfest.

**Comment by devadvance** [comment]
@GiriAakula yes a Telegu translation would be appreciated! I've assigned this issue to you.

**Comment by devadvance** [comment]
I created a placeholder for this here: https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/te/404.html

**Comment by devadvance** [comment]
Hi @GiriAakula are you still interested in translating this?

**Comment by GiriAakula** [comment]
Yes @devadvance. Sorry.. I'm occupied on something else and got no time to work on this. Please give me some more time.
