### ISSUE TITLE
Create an Indonesian translation of the 404 error page

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#86]
Based on the English version of the 404 error page (https://github.com/devadvance/terminalcheatsheet/blob/staging/404.html), create an Indonesian translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/id/404.html.

Look for TODO in the file for suggested places for translations.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by AjiArya** [comment]
@devadvance I'd like to work on this, assign me please.

**Comment by ilesmana** [comment]
Hi @devadvance , I'm working on it.

**Comment by devadvance** [comment]
Assigned to @ilesmana since there's already a PR up for it.
