### ISSUE TITLE
Add Telugu translations for command descriptions

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#88]
This issue is to add Telugu translations for the existing commands found in https://github.com/devadvance/terminalcheatsheet/tree/master/_data/commands

Use `te` (the locale code for Telugu) as the key for the strings.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by shanmukhkalasamudram** [comment]
I'm Interested to do this and I'm a native speaker

**Comment by shanmukhkalasamudram** [comment]
Its completed. Can you pls pr
