### ISSUE TITLE
Add Telugu translations for general strings

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#89]
This issue is to add Telugu translations for the existing strings found in https://github.com/devadvance/terminalcheatsheet/blob/staging/_data/translations.yml

Use `te` (the locale code for Telugu) as the key for the strings.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by gaurang7goel** [comment]
Hi, @devadvance  I want to take this issue.

**Comment by gaurang7goel** [comment]
Pls look over my PR
