### ISSUE TITLE
Add Indonesian translations for command descriptions

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#90]
This issue is to add Indonesian translations for the existing commands found in https://github.com/devadvance/terminalcheatsheet/tree/master/_data/commands

Use `id` (the locale code for Indonesian) as the key for the strings.

**Comment by AjiArya** [comment]
Hello @devadvance I'd like to work on it, please assign me.

**Comment by devadvance** [comment]
@AjiArya thanks! Assigned this issue to you.

**Comment by AjiArya** [comment]
@devadvance Having issue with yamllint #103 . How can I fix this?

**Comment by devadvance** [comment]
@AjiArya I commented in #103 with how I fixed it, and added the `hacktoberfest-accepted` label so the PR will count! Thanks for adding these!

The problem with yamllint was that the line length was a few characters too long. It includes indentation in the count, which may not have been clear in the IDE or tool.
