### ISSUE TITLE
Add Portuguese translations for command descriptions

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#97]
This issue is to add Portuguese translations for the existing commands found in https://github.com/devadvance/terminalcheatsheet/tree/master/_data/commands

Use `pt` (the locale code for Portuguese) as the key for the strings.

Please comment on this issue before starting work so people are informed that you are working on it.

**Comment by sidneymiranda** [comment]
Hi, I'm working on it.

**Comment by devadvance** [comment]
Thanks! Assigned the issue to you.
