### ISSUE TITLE
Add Portuguese translations for general strings

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#98]
This issue is to add Portuguese translations for the existing strings found in https://github.com/devadvance/terminalcheatsheet/blob/staging/_data/translations.yml

Use `pt` (the locale code for Portuguese) as the key for the strings.

**Comment by mailysantos** [comment]
Hey! I can handle this one. Do you accept it?

**Comment by devadvance** [comment]
@mailysantos sure! Assigned this to you.

**Comment by devadvance** [comment]
Fixed by @mailysantos in #101!
